name: Say Hello

on:
    push:
        branches:
            - master

jobs:
    hello_chimus:
        runs-on: ubuntu-22.04
        steps:
            - name: Cancel Previous Redundant Builds
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                access_token: ${{ github.token }}
            - name: Echo the messagee
              run: echo "Hola Chimuelos!"
            - run: sleep 120
            - run: ls -a