name: Say Hello

on:
    push:
        branches:
            - master
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches: [master]

jobs:
    
    avoid_reduncy:
        runs-on: ubuntu-22.04
        steps:
            - name: Cancel Previous Redundant Builds
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                access_token: ${{ github.token }}

    hello_chimus:
        runs-on: ubuntu-22.04
        steps:
            - name: Echo the messagee
              run: echo "Hola Chimuelos!"
            - run: date
            - run: ls -a

    is_pull_request:
        runs-on: ubuntu-22.04
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        steps:
            - run: echo "Esto es una pr"

    bye_chimus:
        runs-on: ubuntu-22.04
        needs: hello_chimus
        steps:
            - name: Echo the messagee
              run: echo "Bye Chimuelos!"